application: zariyaapp1729
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: helloworld.php
- url: /index\.html
  script: test123.php
- url: /smstest
  script: smstest.php
- url: /response_1.php
  script: response_1.php
- url: /phonehome.*
  script: phonehome.php  
- url: /phone_report_1.*
  script: phone_report_1.php  
- url: /phone_report_2.*
  script: phone_report_2.php  
- url: /phone_report_3.*
  script: phone_report_3.php 